name: PSCoreAppInsights

on:
  push:
    paths-ignore:
      - 'README.md'

env:
  MODULE_VERSION: 0.0.1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install InvokeBuild
      run: |
        Install-Module -Name 'InvokeBuild' -Force
    
    - name: Build
      run: |
        Invoke-Build -File .\build\PSCoreAppInsights.build.ps1 -Task 'build' -NewVersionNumber $env:MODULE_VERSION

    - name: Publish
      env:
        PSGALLERY_KEY: ${{ secrets.PSGALLERY_KEY }}
      run: |
        Invoke-Build -File .\build\PSCoreAppInsights.build.ps1 -Task 'publish' -PsGalleryKey $env:PSGALLERY_KEY
      if: github.ref == 'refs/heads/main'

    - uses: actions/upload-artifact@v2
      with:
        name: module
        path: .\build\output\